### ISSUE TITLE
Typo in Example Usage

### ISSUE THREAD

**Issue by halil-erdogan** [matchy233/typst-chi-cv-template#1]
Hey, thanks a lot for great template. I am using that and found a problem in the given example.

```bash
typst --font-path ./fonts resume.typ resume.pdf
```

That is giving error and it should be as following, because we need that `compile` command.

```bash
typst --font-path ./fonts compile resume.typ resume.pdf
```

**Comment by matchy233** [comment]
Many thanks for the feedback! The typo was fixed in the latest commit https://github.com/matchy233/typst-chi-cv-template/commit/b8478ca3c036305fce1d260f44ce9d5f9d321404.
